//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptogram.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptogram.Localization.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string Loc_Authorization {
            get {
                return ResourceManager.GetString("Loc_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Loc_LogEmail {
            get {
                return ResourceManager.GetString("Loc_LogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        public static string Loc_LogLog {
            get {
                return ResourceManager.GetString("Loc_LogLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Loc_LogPass {
            get {
                return ResourceManager.GetString("Loc_LogPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up.
        /// </summary>
        public static string Loc_LogSign {
            get {
                return ResourceManager.GetString("Loc_LogSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Loc_Reg2Back {
            get {
                return ResourceManager.GetString("Loc_Reg2Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose image.
        /// </summary>
        public static string Loc_Reg2ChooseIMG {
            get {
                return ResourceManager.GetString("Loc_Reg2ChooseIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string Loc_Reg2Continue {
            get {
                return ResourceManager.GetString("Loc_Reg2Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your last Name....
        /// </summary>
        public static string Loc_Reg2InpLastName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your name....
        /// </summary>
        public static string Loc_Reg2InpName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your last Name....
        /// </summary>
        public static string Loc_Reg2InpUserName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string Loc_Reg2LastName {
            get {
                return ResourceManager.GetString("Loc_Reg2LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Loc_Reg2Name {
            get {
                return ResourceManager.GetString("Loc_Reg2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share your most intimate safely.
        /// </summary>
        public static string Loc_Reg2Slogan {
            get {
                return ResourceManager.GetString("Loc_Reg2Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string Loc_Reg2UserName {
            get {
                return ResourceManager.GetString("Loc_Reg2UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Cryptogram.
        /// </summary>
        public static string Loc_Reg2Welc {
            get {
                return ResourceManager.GetString("Loc_Reg2Welc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Loc_Reg3Back {
            get {
                return ResourceManager.GetString("Loc_Reg3Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string Loc_Reg3Continue {
            get {
                return ResourceManager.GetString("Loc_Reg3Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It’s look like....
        /// </summary>
        public static string Loc_Reg3CryptoMessage {
            get {
                return ResourceManager.GetString("Loc_Reg3CryptoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get more information.
        /// </summary>
        public static string Loc_Reg3Info {
            get {
                return ResourceManager.GetString("Loc_Reg3Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your encryption key....
        /// </summary>
        public static string Loc_Reg3Key {
            get {
                return ResourceManager.GetString("Loc_Reg3Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input any massage....
        /// </summary>
        public static string Loc_Reg3Message {
            get {
                return ResourceManager.GetString("Loc_Reg3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share your most intimate safely.
        /// </summary>
        public static string Loc_Reg3Slogan {
            get {
                return ResourceManager.GetString("Loc_Reg3Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use base encryption key.
        /// </summary>
        public static string Loc_Reg3UseBaseKey {
            get {
                return ResourceManager.GetString("Loc_Reg3UseBaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cryptogram.
        /// </summary>
        public static string Loc_Reg3Welc {
            get {
                return ResourceManager.GetString("Loc_Reg3Welc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create account.
        /// </summary>
        public static string Loc_RegCreateAcc {
            get {
                return ResourceManager.GetString("Loc_RegCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your email....
        /// </summary>
        public static string Loc_RegEmail {
            get {
                return ResourceManager.GetString("Loc_RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your password....
        /// </summary>
        public static string Loc_RegPass {
            get {
                return ResourceManager.GetString("Loc_RegPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password....
        /// </summary>
        public static string Loc_RegRepPass {
            get {
                return ResourceManager.GetString("Loc_RegRepPass", resourceCulture);
            }
        }
    }
}
