//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptogram.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rus() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cryptogram.Localization.Rus", typeof(Rus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить изменения.
        /// </summary>
        public static string Loc_AplCh {
            get {
                return ResourceManager.GetString("Loc_AplCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string Loc_Authorization {
            get {
                return ResourceManager.GetString("Loc_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш статус....
        /// </summary>
        public static string Loc_InpStatuc {
            get {
                return ResourceManager.GetString("Loc_InpStatuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронный адрес.
        /// </summary>
        public static string Loc_LogEmail {
            get {
                return ResourceManager.GetString("Loc_LogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Loc_LogLog {
            get {
                return ResourceManager.GetString("Loc_LogLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Loc_LogOut {
            get {
                return ResourceManager.GetString("Loc_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Loc_LogPass {
            get {
                return ResourceManager.GetString("Loc_LogPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Loc_LogSign {
            get {
                return ResourceManager.GetString("Loc_LogSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я принимаю политику конфиденциальности.
        /// </summary>
        public static string Loc_PrivatePolice {
            get {
                return ResourceManager.GetString("Loc_PrivatePolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Loc_Reg2Back {
            get {
                return ResourceManager.GetString("Loc_Reg2Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите аватар.
        /// </summary>
        public static string Loc_Reg2ChooseIMG {
            get {
                return ResourceManager.GetString("Loc_Reg2ChooseIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Далее.
        /// </summary>
        public static string Loc_Reg2Continue {
            get {
                return ResourceManager.GetString("Loc_Reg2Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        public static string Loc_Reg2Email {
            get {
                return ResourceManager.GetString("Loc_Reg2Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите вашу фамилию.
        /// </summary>
        public static string Loc_Reg2InpLastName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваше имя....
        /// </summary>
        public static string Loc_Reg2InpName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите username.
        /// </summary>
        public static string Loc_Reg2InpUserName {
            get {
                return ResourceManager.GetString("Loc_Reg2InpUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string Loc_Reg2LastName {
            get {
                return ResourceManager.GetString("Loc_Reg2LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Loc_Reg2Name {
            get {
                return ResourceManager.GetString("Loc_Reg2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Делитесь самым сокровенным безопасно.
        /// </summary>
        public static string Loc_Reg2Slogan {
            get {
                return ResourceManager.GetString("Loc_Reg2Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string Loc_Reg2UserName {
            get {
                return ResourceManager.GetString("Loc_Reg2UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в Cryptogram.
        /// </summary>
        public static string Loc_Reg2Welc {
            get {
                return ResourceManager.GetString("Loc_Reg2Welc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Loc_Reg3Back {
            get {
                return ResourceManager.GetString("Loc_Reg3Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Далее.
        /// </summary>
        public static string Loc_Reg3Continue {
            get {
                return ResourceManager.GetString("Loc_Reg3Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример шифрования.
        /// </summary>
        public static string Loc_Reg3CryptoMessage {
            get {
                return ResourceManager.GetString("Loc_Reg3CryptoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шифр-ключ.
        /// </summary>
        public static string Loc_Reg3EncryptKey {
            get {
                return ResourceManager.GetString("Loc_Reg3EncryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узнать больше.
        /// </summary>
        public static string Loc_Reg3Info {
            get {
                return ResourceManager.GetString("Loc_Reg3Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ключ шифровки.
        /// </summary>
        public static string Loc_Reg3Key {
            get {
                return ResourceManager.GetString("Loc_Reg3Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите любой текст.
        /// </summary>
        public static string Loc_Reg3Message {
            get {
                return ResourceManager.GetString("Loc_Reg3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Делитесь самым сокровенным безопасно.
        /// </summary>
        public static string Loc_Reg3Slogan {
            get {
                return ResourceManager.GetString("Loc_Reg3Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайный шифр-ключ.
        /// </summary>
        public static string Loc_Reg3UseBaseKey {
            get {
                return ResourceManager.GetString("Loc_Reg3UseBaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Cryptogram.
        /// </summary>
        public static string Loc_Reg3Welc {
            get {
                return ResourceManager.GetString("Loc_Reg3Welc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать аккаунт.
        /// </summary>
        public static string Loc_RegCreateAcc {
            get {
                return ResourceManager.GetString("Loc_RegCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите вашу почту....
        /// </summary>
        public static string Loc_RegEmail {
            get {
                return ResourceManager.GetString("Loc_RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль....
        /// </summary>
        public static string Loc_RegPass {
            get {
                return ResourceManager.GetString("Loc_RegPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль....
        /// </summary>
        public static string Loc_RegRepPass {
            get {
                return ResourceManager.GetString("Loc_RegRepPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Loc_Status {
            get {
                return ResourceManager.GetString("Loc_Status", resourceCulture);
            }
        }
    }
}
